### ISSUE TITLE
Blend version of your attack

### ISSUE THREAD

**Issue by ivansabolic** [Ben-Schneider-code/Universal-Backdoor-Attacks#1]
Hey Ben,

Thanks a lot for your work and clean code! 

While reproducing your work, I was having trouble running **Blend** version of the attack. I tried setting `backdoor_args.function` to `blend` while keeping `backdoor_args.name` as `universal-backdoor`, however that resulted with error. Am I maybe misinterpreting something in your code?

**Comment by Ben-Schneider-code** [comment]
Hi!
I messed up when I updated the naming in an attack enum to align more with the paper. I think I have now fixed the issue (but I do not currently have the computing resources to verify everything). I've added configs to make recreating the blend attack and its corresponding baseline easier.

Please let me know if you have issues with anything else,
Ben

**Comment by ivansabolic** [comment]
Hey Ben,

Sorry for the late response from my side. Yep, the issue is resolved, thanks for marking it as resolved.

Also, setting `x = x.cuda()` inside the `embed` function of `FunctionalMapPoison` class speeds up the whole process of trigger embedding.
